### ISSUE TITLE
nemo-terminal doesn't work with gtk-3.14

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/nemo-extensions#72]
```
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo_terminal.py", line 466, in _on_crowbar_parent_set
    nterm = NemoTerminal(self._uri, self._window)
  File "/usr/share/nemo-python/extensions/nemo_terminal.py", line 87, in __init__
    self.shell_pid = self.term.fork_command_full(Vte.PtyFlags.DEFAULT,
AttributeError: 'Terminal' object has no attribute 'fork_command_full'
```
